ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.MEVtrap]
path = "out/MEVTrap.sol/MEVTrap.json"
response_contract = "0xAD8e31Da04D1dE260854B97f9f49d7945e4e9032"
response_function = "logSandwich(uint256,address,address,address,address,uint256,uint256,bytes32,bytes32,bytes32)"
cooldown_period_blocks = 2
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 3
private = true
whitelist = ["0x90b3Cc93161B110Dee457D9B7B6B760034B3E53d"]
address = "0xA32452bec611cc0E16B6937BDA863Dc1860072D3"
